feat: Deckbuilder endpoints
JoaquinLeonArg/wdml-mtg pull request #14
Opened 2024-03-14 18:27 UTC by fbianco32

2024-03-14 19:57 UTC, JoaquinLeonArg requested changes

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/logic.go
> +}
Me copa poner de que es el id cuando es asi para que sea mas legible. "deckID" en este caso, lo mismo en las otras funciones

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/logic.go
> +func CreateEmptyDeck(ownerId string, req CreateEmptyDeckRequest) error {
Para reducir el coupling entre la capa de logica y la de la API, es mejor pasarle los argumentos uno por uno en vez de la Request entera. Lo mismo va para los otros métodos.

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	r.HandleFunc("/new", CreateEmptyDeckHandler).Methods(http.MethodPost)
Post a / mejor?

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	r.HandleFunc("/removeCard", RemoveCardFromDeckHandler).Methods(http.MethodPost)
`/card`, y usar post para agregar y delete para sacar?

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +		w.WriteHeader(http.StatusInternalServerError)
Devolver el error especifico en lugar de 500. Lo mismo en los demás.

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	// Add the booster packs to each player, checking if the user is allowed to add them and if they are valid packs
Revisar comments en general

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	filter := bson.D{{Key: "tournament_player_id", Value: dbTournamentPlayerID}}
```suggestion
	filter := bson.M{"tournament_player_id": dbTournamentPlayerID}
```

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	log.Debug().Str("created deck id", deck.ID.String())
```suggestion
	log.Debug().Str("deck_id", deck.ID.String()).Msg("created deck")
```
Igual despues deberíamos mejorar el debugging en db en general

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	Card   domain.OwnedCard `json:"card"`
Debería venir el id de la ownedCard nada mas. Lo demás lo sacamos de la db.

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	}
Aca solo nos llega el ownedCard.id, y en la transaction la buscamos y así sabemos cuantas cartas tiene el player. Sino estamos confiando en la info que llega desde el frontend.
También necesitamos primero saber cuantas copias de la carta el deck ya tiene, asi consideramos el total y no solo las que se añaden.

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	defer session.EndSession(ctx)
Deberias armar una transaction y meter las queries adentro asi nos aseguramos de no dejar un estado inconsistente

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	newDeckCards := make([]domain.DeckCard, 0)
Me parece que no hace falta rearmar la lista, simplemente podés agregarle un elemento a la original, o actualizar el que ya existe cuando iterás. Mas rápido y usa menos memoria.

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/domain/deck.go
> +	DeckId    primitive.ObjectID `bson:"deck_id" json:"deck_id"`
Si forman parte del struct de Deck no hace falta que tengan id propio ni referencia al otro.

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/domain/deck.go
> +	OwnedCard OwnedCard          `bson:"owned_card" json:"owned_card"`
Solo una referencia al id del OwnedCard, asi no lo duplicamos aca (ej si abre mas copias de esa carta, aca va a quedar viejo)

2024-03-14 19:57 UTC, JoaquinLeonArg commented on backend/internal/booster_gen/boosters.go
> +			filter := fmt.Sprintf("%s %s game:paper", slot.Filter, chosenOption.Filter)
💯💯💯

2024-03-15 17:59 UTC, fbianco32 commented on backend/db/deck.go
> +	}
El checkeo adentro de la transaction se hace, la idea de esa linea era un check rapido y naive para fallar rapido si se manda mas cartas que las que hay en coleccion directamente, es medio redundante

2024-03-15 18:28 UTC, JoaquinLeonArg requested changes

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	// Get all available booster packs for this tournament
Comment

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	// Add the booster packs to each player, checking if the user is allowed to add them and if they are valid packs
Comment

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/api/routes/deck/router.go
> +	// Add the booster packs to each player, checking if the user is allowed to add them and if they are valid packs
Comment

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	// Find pack
Comment

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	// Find pack
Comment

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	// Decode deck
decks

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	log.Debug().Str("created deck id", deck.ID.String())
Creo que te falto esto

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +			}
Podemos comparar `ownedCard.Id == deckCard.OwnedCardId` para ver si ya la tiene en vez de traer cada una y comparar set y collector? Si no estamos haciendo N queries. Y hacer break cuando la encontramos.

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +	}
Aca tambien iria en una transaction

2024-03-15 18:28 UTC, JoaquinLeonArg commented on backend/db/deck.go
> +			ownedDeckCard.CardData.CollectorNumber == ownedCard.CardData.CollectorNumber &&
Lo mismo, chequear los ids nomas para no pedir cada carta por separado a la db

2024-03-15 18:34 UTC, fbianco32 commented on backend/db/deck.go
> +	log.Debug().Str("created deck id", deck.ID.String())
yep, me lo comi

2024-03-15 18:36 UTC, fbianco32 commented on backend/db/deck.go
> +			}
Break cuando la encontramos no tiene 100% sentido porque igual queremos ver todo el mazo para sumar las amounts de todas las boards, si a todo lo demas

2024-03-15 18:52 UTC, JoaquinLeonArg approved these changes

2024-03-15 18:52 UTC, merged